### ISSUE TITLE
Some missing settings from the original Redshift

### ISSUE THREAD

**Issue by CubeTheThird** [benzea/gnome-shell-extension-redshift#12] opened 2017-01-16 00:03 UTC
I'm not sure if the gnome settings daemon version offers different settings, but several options appear to be missing in the configuration menu:
brightness: a value between 0 and 1, configurable between day and night
gamma: a fixed value, or triplet for each colour channel
manual location: latitude and longitude manually chosen, instead of using an internet service

I don't know if it is possible to add or implement these, but I figured I would bring it up to see.

**Comment by benzea** [comment] 2017-01-16 00:31
I consider all these somewhat out of scope or to complicated:
 1. brightness: The issue is that you could both change the gamma curve or the backlight. This requires more knowledge (which I am not sure exists) and integration into other pieces of software. I know it would be nice, but I am not willing to work on it personally. If you *really* care, open an issue about just this, maybe someone other than me picks it up.
 2. Making gamma curve changes is not the scope of this tool. The whole point of this implementation is that normal colour profiles that can be configured through gnome-control-center work fine.
 3. I would consider fixed time a very good alternative. It would be easy to implement (just set the last known location to a different value). If you have a good reason why fixed time is not an option, then please explain.

**Closed as completed by benzea** 2017-01-16 00:31 UTC

**Comment by CubeTheThird** [comment] 2017-01-16 01:24
After looking into the patch being applied to the settings daemon, I understand that it would be more difficult to implement the brightness option, as currently a somewhat linear colour temperature is all that is used for input. I will consider opening a new issue for it, since the brightness (strictly gamma, not backlight) plays a big role (IMO) in the effectiveness of what Redshift accomplishes. I'll do some more investigating into this however.

As for the manual location, I was more curious since the original Redshift uses that instead of time settings, so it would be easier to copy/paste those to get the same results from the other config.
